### PR TITLE
New linter

### PR DESCRIPTION
**Pull request by keur**
### Submitter Checklist

- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Tested on Firefox (`npm run firefox`)
- [x] Tested on Chromium (`npm run chromium`)

### CODE REVIEW

**Comment by yvbbrjdr** [comment]
I'm not sure if I like
```javascript
if ( expression ) {
    statement;
}
```
and

```javascript
while ( expression ) {
    statement;
}
```

**Comment by keur** [comment]
@yvbbrjdr You prefer those to be on one line?

**Comment by yvbbrjdr** [comment]
Nah I mean the spaces

**Comment by keur** [comment]
I like the spaces for cases like this:

```
return new Promise<any>( ( resolve: ( _: any ) => void ) => { ... 
```

But I can live without it.

**Comment by yvbbrjdr** [comment]
I like your case too.

**Comment by keur** [comment]
Your call. I can remove that rule and we can re-add it later.

**Pull request merged**
